apiVersion: v1
kind: Service
metadata:
  name: biddinggo-mariadb
  namespace: biddinggo
  labels:
    app: biddinggo-mariadb
spec:
  type: ClusterIP
  selector:
    app: biddinggo-mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
