spring:
  application:
    name: bidding-go
  profiles:
    default: local
  config:
    import: optional:file:.env[.properties]
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    '[org.springframework.web]': info
    '[org.springframework.security]': info
    '[org.mybatis]': debug
    '[org.mariadb.jdbc.client.impl]': info
    '[org.springframework.data.redis]': info
    '[io.lettuce.core]': info
