apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: biddinggo
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord: biddinggo-discord
    notifications.argoproj.io/subscribe.on-sync-failed.discord: biddinggo-discord
    notifications.argoproj.io/subscribe.on-health-degraded.discord: biddinggo-discord
spec:
  project: default
  source:
    repoURL: https://github.com/alskung1101/be25-2nd-biddingmate-biddinggo.git
    targetRevision: feature/deploy-setup
    path: k8s/dockerhub
  destination:
    server: https://kubernetes.default.svc
    namespace: biddinggo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
