apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
images:
  - name: biddinggo-backend
    newName: docker.io/alskung/biddinggo-backend
    newTag: 47d6fcc
patches:
  - path: backend-image-pull-policy.yaml
