crds:
  install: false
  keep: true

configs:
  params:
    server.insecure: true

server:
  service:
    type: NodePort
    nodePortHttp: 30090
    nodePortHttps: 30490

notifications:
  enabled: true
