apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mariadb-service.yaml
  - mariadb-statefulset.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
  - backend-configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-pod-disruption-budget.yaml
